apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
  labels:
    name: nginx-depl
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end
